name: XGAP
version: "4.31"
date: 2022-02-17
description: |
    a graphical user interface for GAP

authors:
    - name: Frank Celler
      url: http://celler.de/
    - name: Max Neunhöffer
      url: http://www-groups.mcs.st-and.ac.uk/~neunhoef

maintainers:
    - name: Max Horn
      url: https://www.quendi.de/math

GAP: ">=4.7"

www: https://gap-packages.github.io/xgap
readme: README
packageinfo: https://gap-packages.github.io/xgap/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/xgap/releases/download/v4.31/xgap-4.31.tar.gz

abstract: |
    The <span class="pkgname">XGAP</span> package allows to use graphics in GAP.

status: accepted
doc-html: htm/chapters.htm
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>CHN22</span>]   <b class='BibAuthor'>Celler, F., Horn, M. and Neunhöffer, M.</b>,
     <i class='BibTitle'>XGAP, a graphical user interface for GAP,
             Version 4.31</i>
     (<span class='BibYear'>2022</span>)<br />
    (<span class='BibNote'>Refereed GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/xgap">https://gap-packages.github.io/xgap</a></span>.
    </p>
    

bibtex: |
    @misc{ XGAP4.31,
      author =           {Celler, F. and Horn, M. and Neunh{\"o}ffer, M.},
      title =            {{XGAP},  a graphical user interface for GAP, {V}ersion
                          4.31},
      month =            {Feb},
      year =             {2022},
      note =             {Refereed GAP package},
      howpublished =     {\href            {https://gap-packages.github.io/xgap}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{xgap}}},
      printedkey =       {CHN22}
    }

