name: XGAP
version: 4.28
date: 2018-09-12
description: |
    a graphical user interface for GAP

authors:
    - name: Frank Celler
      url: http://celler.de/
    - name: Max Neunhöffer
      url: http://www-groups.mcs.st-and.ac.uk/~neunhoef

maintainers:
    - name: Max Horn
      url: http://www.quendi.de/math

GAP: ">=4.7"

www: https://gap-packages.github.io/xgap
readme: README
packageinfo: https://gap-packages.github.io/xgap/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/xgap/releases/download/v4.28/xgap-4.28.tar.gz

abstract: |
    The <span class="pkgname">XGAP</span> package allows to use graphics in GAP.

status: accepted
doc-html: htm/chapters.htm
doc-pdf: doc/manual.pdf
