#!/bin/bash
# Shell-Script to tar the distribution of xgap
# This should be called right after the checkout and after making the
# documentation and html files without compiled versions in the current
# directory tree. It should be called from the GAP `pkg' directory.

# Change this for the latest revision:
# (Last digit is patchlevel) 
TARFILE=xgap-4.23

rm -f $TARFILE.tar.gz

tar czvf $TARFILE.tar.gz xgap/{README*,Makefile.in,configure,configure.in,init.g,PackageInfo.g} xgap/Changelog.* xgap/xgap.shi xgap/cnf/{M*,c*,i*} xgap/doc/{*.tex,*.msk,*.config,Makefile,manual.{six,bib,mst}} xgap/doc/manual.{dvi,pdf} xgap/doc/manual.six xgap/doc/manual.pdf xgap/examples/* xgap/htm/* xgap/htm/* xgap/lib/{*.g,*.gi,*.gd} xgap/src.x11/{*.c,*.h} xgap/src.x11/bitmaps/*

