#!/bin/sh
# $Id: zooit,v 1.16 2002/04/23 10:45:18 gap Exp $
# Shell-Script to zoo the distribution of xgap
# This should be called right after the checkout and after making the
# documentation and html files without compiled versions in the current
# directory tree. It should be called from the GAP `pkg' directory.

# Change this for the latest revision:
# (Last digit is patchlevel) 
ZOOFILE=xgap4r15

rm -f TEXTCOM BINCOM
echo '!TEXT!' > TEXTCOM
echo '/END'   >>TEXTCOM
echo '!BINARY!'>BINCOM
echo '/END'   >>BINCOM

rm -f $ZOOFILE.zoo

for i in xgap/{README,Makefile.in,configure,configure.in,init.g}; do
  zoo ahc $ZOOFILE.zoo $i <TEXTCOM
done

for i in xgap/Changelog.* ; do
  zoo ahc $ZOOFILE.zoo $i <TEXTCOM
done

for i in xgap/xgap.shi ; do
  zoo ahc $ZOOFILE.zoo $i <TEXTCOM
done

for i in xgap/cnf/{M*,c*}; do
  zoo ahc $ZOOFILE.zoo $i <TEXTCOM
done

for i in xgap/doc/{*.tex,*.msk,*.config,Makefile,manual.{six,bib,mst}}; do
  zoo ahc $ZOOFILE.zoo $i <TEXTCOM
done
zoo ahc $ZOOFILE.zoo xgap/doc/manual.dvi <BINCOM

for i in xgap/examples/*; do
  zoo ahc $ZOOFILE.zoo $i <TEXTCOM
done

for i in xgap/htm/*; do
  zoo ahc $ZOOFILE.zoo $i <TEXTCOM
done

for i in xgap/lib/{*.g,*.gi,*.gd}; do
  zoo ahc $ZOOFILE.zoo $i <TEXTCOM
done

for i in xgap/src.x11/{*.c,*.h}; do
  zoo ahc $ZOOFILE.zoo $i <TEXTCOM
done

for i in xgap/src.x11/bitmaps/*; do
  zoo ahc $ZOOFILE.zoo $i <BINCOM
done

rm -f TEXTCOM BINCOM


