name: CI

# Trigger the workflow on push or pull request
on:
  push:
    branches:
      - master
  pull_request:

# the `concurrency` settings ensure that not too many CI jobs run in parallel
concurrency:
  # group by workflow and ref; the last slightly strange component ensures that for pull
  # requests, we limit to 1 concurrent job, but for the master branch we don't
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/master' || github.run_number }}
  # Cancel intermediate builds, but only if it is a pull request build.
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  # The CI test job
  test:
    name: ${{ matrix.gap-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gap-version:
          - 'devel'
          - '4.14'
          - '4.13'
          - '4.12'
          - '4.11'
          - '4.10'
          - '4.9'

    steps:
      - uses: actions/checkout@v5
      - name: 'Install X Window development files'
        run: |
          sudo apt-get update
          sudo apt-get install libx11-dev libxaw7-dev
      - uses: gap-actions/setup-gap@v3
        with:
          gap-version: ${{ matrix.gap-version }}
      - uses: gap-actions/build-pkg@v2
      - uses: gap-actions/run-pkg-tests@v4
      - uses: gap-actions/run-pkg-tests@v4
        with:
          mode: onlyneeded
      - uses: gap-actions/process-coverage@v3
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  # The documentation job
  manual:
    name: Build manuals
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: gap-actions/setup-gap@v3
      - uses: gap-actions/build-pkg-docs@v2
        with:
          use-latex: 'true'
          warnings-as-errors: 'false'  # see https://github.com/gap-actions/build-pkg-docs/issues/34
      - name: 'Upload documentation'
        uses: actions/upload-artifact@v4
        with:
          name: manual
          path: ./doc/manual.pdf
          if-no-files-found: error
